---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/16 15:16
---

local redis_instance = require 'redis_helper'

redis_instance.get_connection()